---
- name: remove packages
  hosts: webserver
  remote_user: root
  become: true
  gather_facts: true
  vars_files:
    - remove-pkgs.yaml
  tasks:
    - name: remove packages
      yum:
        name: "{{ pkgs }}"
        state: absent 
