---
- name: copy the file
  become: true
  hosts: all
  remote_user: root
  tasks:
    - name: copy the files
      copy: 
        src: /root/project/test.txt
        dest: /
        owner: root
        mode: 0700
      when: ansible_distribution == "Ubuntu"  
    - name: copy the files
      copy: 
        src: /root/project/project1/index.html
        dest: /
        owner: root
        mode: 0700
      when: ansible_distribution == "Rocky"  
