---
- name: install http server
  hosts: webserver
  remote_user: root
  become: true
  gather_facts: true
  tasks:
    - name: install http 
      yum:
        name: httpd
        state: latest
    - name: start the service
      service:
        name: httpd
        state: started
        enabled: yes
    - name: create index file
      file:
        path: /var/www/html/index.html
        state: touch
    - name: add content to index.html file
      lineinfile:
        path: /var/www/html/index.html
        line: " Welcome to the webserver "
    - name: restart the service
      service:
        name: httpd
        state: restarted

